SET NOCOUNT ON;

DECLARE @sf tinyint;
DECLARE @sf1 tinyint;
DECLARE @tp float, @tpb float, @tpaid float, @tret float, @tnd float, @tqty float;
DECLARE @S_ID int = 0;
DECLARE @TRAN_NO int = 0;
DECLARE @TRAN_BARNCH varchar(10) = 'A';
DECLARE @dt datetime = GETDATE();

EXEC dbo.SALE_INVOICE_SAVE
  @S_ID = @S_ID, @S_DATE = @dt, @CUST_ID = 1, @CUST_NAME = 'test pos', @COMM_ID = 0,
  @S_STATUES = 0, @S_NOTE = '', @S_DISCOUNT = 0, @S_TAX1 = 0, @S_TAX2 = 0, @S_SHIPMENT = 0,
  @USERS_ID = 11, @COMM_PERCENT_FLAG = 0, @Flag = 5, @BRANCH = 0,
  @ACC_DEBIT = 0, @ACC_CREDIT = 0, @ACC_DIS_DEBIT = 0, @ACC_TAX_CREDIT = 0,
  @TRAN_ID = 0, @TRAN_NO = @TRAN_NO, @TRAN_BARNCH = @TRAN_BARNCH, @CB_TAKE = 0,
  @ACC_T_DEBIT1 = 0, @ACC_T_CREDIT1 = 0, @ACC_T_M_S_DEBIT_S1 = 0, @ACC_T_M_S_CREDIT_S1 = 0,
  @G_DEFULT_BANK1 = 0, @STATE_FLAG = @sf OUTPUT;

SELECT @TRAN_NO = MAX(TRAN_NO) FROM dbo.SALE_INVOICE WHERE TRAN_BARNCH = 'A';
SELECT @S_ID = S_ID FROM dbo.SALE_INVOICE WHERE TRAN_NO = @TRAN_NO AND TRAN_BARNCH = 'A';
SELECT @S_ID AS new_s_id, @TRAN_NO AS tran_no;

EXEC dbo.SALE_INVOICE_SAVE
  @S_ID = @S_ID, @S_DATE = @dt, @CUST_ID = 1, @CUST_NAME = 'test pos', @COMM_ID = 0,
  @S_STATUES = 0, @S_NOTE = '', @S_DISCOUNT = 0, @S_TAX1 = 0, @S_TAX2 = 0, @S_SHIPMENT = 0,
  @USERS_ID = 11, @COMM_PERCENT_FLAG = 0, @Flag = 0, @BRANCH = 0,
  @ACC_DEBIT = 0, @ACC_CREDIT = 0, @ACC_DIS_DEBIT = 0, @ACC_TAX_CREDIT = 0,
  @TRAN_ID = 0, @TRAN_NO = @TRAN_NO, @TRAN_BARNCH = @TRAN_BARNCH, @CB_TAKE = 0,
  @ACC_T_DEBIT1 = 0, @ACC_T_CREDIT1 = 0, @ACC_T_M_S_DEBIT_S1 = 0, @ACC_T_M_S_CREDIT_S1 = 0,
  @G_DEFULT_BANK1 = 0, @STATE_FLAG = @sf OUTPUT;

EXEC dbo.SALE_ITEMS_SAVE
  @PROC_TYPE = 1, @S_ITEM_ID = 0, @S_ID = @S_ID, @ITEM_ID = 16491, @STORE_ID = 1,
  @QTY = 1, @UNIT_ID = 92, @UNIT_QTY = 1, @CATEOGRY1 = '', @CATEOGRY2 = '', @CATEOGRY3 = NULL, @CAT3 = 0,
  @PRICE = 10, @LAST_COST = 5, @AVER_COST = 5, @PUBLIC_PRICE = 0, @S_ITEM_INVISIBLE = 1,
  @COLLECT_ID = 0, @AGENT_PERCENT = 0, @OFS = 0, @F1 = 0, @ITEMS_ORDER = 0,
  @CUST_ID = 1, @COMM_ID = 0, @STATE_FLAG1 = 0, @BARCODE = '090347564785', @COLLECT_FLAG = 0,
  @USERS_ID = 11, @H = 0, @W = 0, @Q = 0, @RING = 0, @PULISH = 0, @MADE = 0, @CUT = 0,
  @ASSEMP = 0, @STREACH = 0, @SIZE = '', @TATIM = 0, @SIZE_RING = '', @COLOR = '', @COLOR_PRICE = 0,
  @SUM_ALL_ITEMS = 0, @DETAILS = 0,
  @STATE_FLAG = @sf1 OUTPUT, @TOTAL_PRICE = @tp OUTPUT, @TOTAL_PRICE_BEFORE = @tpb OUTPUT,
  @TOTAL_PAIED = @tpaid OUTPUT, @TOTAL_RETURN = @tret OUTPUT, @TOTAL_NOT_DONE = @tnd OUTPUT,
  @TOTAL_QTY = @tqty OUTPUT;

SELECT @sf1 AS item_state, @tp AS total;
SELECT COUNT(*) AS item_count FROM dbo.SALE_ITEMS WHERE S_ID = @S_ID;

-- cleanup test draft
EXEC dbo.SALE_INVOICE_SAVE
  @S_ID = @S_ID, @S_DATE = @dt, @CUST_ID = 1, @CUST_NAME = 'test', @COMM_ID = 0,
  @S_STATUES = 0, @S_NOTE = 'pos test cancel', @S_DISCOUNT = 0, @S_TAX1 = 0, @S_TAX2 = 0, @S_SHIPMENT = 0,
  @USERS_ID = 11, @COMM_PERCENT_FLAG = 0, @Flag = 4, @BRANCH = 0,
  @ACC_DEBIT = 0, @ACC_CREDIT = 0, @ACC_DIS_DEBIT = 0, @ACC_TAX_CREDIT = 0,
  @TRAN_ID = 0, @TRAN_NO = @TRAN_NO, @TRAN_BARNCH = @TRAN_BARNCH, @CB_TAKE = 0,
  @ACC_T_DEBIT1 = 0, @ACC_T_CREDIT1 = 0, @ACC_T_M_S_DEBIT_S1 = 0, @ACC_T_M_S_CREDIT_S1 = 0,
  @G_DEFULT_BANK1 = 0, @STATE_FLAG = @sf OUTPUT;

SELECT @sf AS cancel_state;
